// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using multitenant_vargas.Api.Data;

#nullable disable

namespace multitenant_vargas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922034455_AgregarAutenticacionRolesYRefreshTokens")]
    partial class AgregarAutenticacionRolesYRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.Property<bool>("Stock")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expira_en");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Codigo = "administrador",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Codigo = "vendedor",
                            Nombre = "Vendedor"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Codigo = "caja",
                            Nombre = "Caja"
                        });
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("password_hash");

                    b.Property<long?>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol_id");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Email = "admin@vargas.com",
                            Nombre = "Administrador",
                            PasswordHash = "6NNEj6LktQCltNZtjjIo5w==.grD8rHC6e2kQnccKe/cA7ZRhepankZ8HytggkiWoaEs=",
                            RolId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Email = "vendedor@vargas.com",
                            Nombre = "Vendedor",
                            PasswordHash = "5GLEmu+5ongNqHhy2qoJoQ==.NeR4dtZ7sbTN+x/bLhB7yEVDgytvJ5zIIUnZj+wBb6Y=",
                            RolId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Email = "sinrol@vargas.com",
                            Nombre = "Usuario sin rol",
                            PasswordHash = "jFW4Vo0rXf8AyFaYIHA8tA==.eRjLsnfog9iFPU5DRCiI33vL3gCZY/U7+LtIOoVEYzI="
                        });
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .HasConstraintName("fk_usuarios_roles_rol_id");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
