// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using multitenant_vargas.Api.Data;

#nullable disable

namespace multitenant_vargas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre_empresa");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.ToTable("empresas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            NombreEmpresa = "Vargas"
                        });
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("cliente");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("ak_pedidos_id_empresa_id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_pedidos_empresa_id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_pedidos_fecha");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_pedidos_usuario_id");

                    b.ToTable("pedidos", null, t =>
                        {
                            t.HasCheckConstraint("ck_pedidos_estado", "BINARY estado IN ('En preparacion', 'Listo', 'Cancelado')");
                        });
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<long?>("ProductoId")
                        .HasColumnType("bigint")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_pedido_items");

                    b.HasIndex("PedidoId", "EmpresaId")
                        .HasDatabaseName("ix_pedido_items_pedido_id_empresa_id");

                    b.HasIndex("ProductoId", "EmpresaId")
                        .HasDatabaseName("ix_pedido_items_producto_id_empresa_id");

                    b.ToTable("pedido_items", (string)null);
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("descripcion");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("foto_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.Property<bool>("Stock")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasAlternateKey("Id", "EmpresaId")
                        .HasName("ak_productos_id_empresa_id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_productos_empresa_id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expira_en");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revocado_en");

                    b.Property<string>("RolSesion")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("rol_sesion");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<int>("VersionAmbito")
                        .HasColumnType("int")
                        .HasColumnName("version_ambito");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Codigo = "administrador",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Codigo = "vendedor",
                            Nombre = "Vendedor"
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Codigo = "caja",
                            Nombre = "Caja"
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            Codigo = "superadmin",
                            Nombre = "Superadmin"
                        });
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("password_hash");

                    b.Property<long?>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarios_rol_id");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Email = "admin@vargas.com",
                            Nombre = "Administrador",
                            PasswordHash = "6NNEj6LktQCltNZtjjIo5w==.grD8rHC6e2kQnccKe/cA7ZRhepankZ8HytggkiWoaEs=",
                            RolId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Email = "vendedor@vargas.com",
                            Nombre = "Vendedor",
                            PasswordHash = "5GLEmu+5ongNqHhy2qoJoQ==.NeR4dtZ7sbTN+x/bLhB7yEVDgytvJ5zIIUnZj+wBb6Y=",
                            RolId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Email = "sinrol@vargas.com",
                            Nombre = "Usuario sin rol",
                            PasswordHash = "jFW4Vo0rXf8AyFaYIHA8tA==.eRjLsnfog9iFPU5DRCiI33vL3gCZY/U7+LtIOoVEYzI="
                        });
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("EmpresaId")
                        .HasColumnType("bigint")
                        .HasColumnName("empresa_id");

                    b.Property<long>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_roles");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_usuario_roles_empresa_id");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_roles_rol_id");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_roles_usuario_id_empresa_id");

                    b.ToTable("usuario_roles", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_roles_ambito", "(rol_id = 4 AND empresa_id IS NULL) OR (rol_id IN (1, 2, 3) AND empresa_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_empresas_empresa_id");

                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuarios_usuario_id");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_items_pedidos_pedido_id_empresa_id");

                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId", "EmpresaId")
                        .HasPrincipalKey("Id", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedido_items_productos_producto_id_empresa_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Producto", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_productos_empresas_empresa_id");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .HasConstraintName("fk_usuarios_roles_rol_id");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuario_roles_empresas_empresa_id");

                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_roles_rol_id");

                    b.HasOne("multitenant_vargas.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_roles_usuarios_usuario_id");

                    b.Navigation("Empresa");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("multitenant_vargas.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
